#!/usr/bin/env sh
if ! head -1 "$1" | grep -qE "^. (feat|fix|WIP|ci|chore|docs|test|style|codestyle|refactor|dependency|perf|build|revert|mock|poop)(\(.+?\))?: .{1,}$"; then
    printf "\n\e[0;31mCommit aborted. The \e[1;34mTAG\e[0m\e[0;31m is an invalid type.\n\n\e[0m" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    printf "\n\e[0;31mCommit aborted. The\e[1;34m MESSAGE \e[0m\e[0;31mdis too long \e[0m\e[1;34m(more than 88 characters). \e[0m\n\n" >&2
    exit 1
fi